addpath(genpath('mEpiTools'))
addpath('data')
close all
clear all
span = 7;
mean_si = 4.7;
std_si = 2.9;
incid = importData('Brunei_Darussalam',[]);
T = length(incid.I);
t_start = 7:T-7; 
t_end = t_start+7;

res = estimate_R(incid, ...
    'parametric_si',...
    'config', make_config(...
    't_start',t_start,'t_end',t_end,... %mean_si makes first curve rise middle curve lower
    'mean_si', 4.8,...
    'std_si', 4.4));
plot(res,'what',['incid','R','IR'],...
    'opt_I',options(...
    'title',sprintf('%s COVID-19\nEpidemic curve',incid.name),...
    'plot_type','bar'),...
    'opt_IR',options('plot_type','bar'))
