addpath(genpath('mEpiTools'))
addpath(genpath('mR0'))
clear all
span = 7;
mean_si = 4.7;
std_si = 2.9;
% data for new wave of Covid-19 in Slovenia
incid=importData('Brunei_Darussalam',[]);
incid.population = 440333

% use default 7-days window length
config = make_config('mean_si',4.7,'std_si',2.9);
res    = estimate_R(incid,'parametric_si',config);
fprintf('R = %g (CI %g - %g)  IR = %d   AR = %d\n',...
    res.mean_posterior(end),...
    res.quantile_005_posterior(end),...
    res.quantile_095_posterior(end),...
    round(res.IR(end),0),...
    round(res.AR(end),0))
%close all
T = length(incid.I);
plot(res,'what','all','options_I',options('plot_type','bar'));
t_start = 2:T-span+1; % starting at 2 as conditional on the past observations
t_end = t_start + span-1;
res = estimate_R(incid, ...
    'parametric_si',...
    'config', make_config(...
    't_start',t_start,'t_end',t_end,...
    'mean_si', mean_si,...
    'std_si', std_si));
plot(res,'what',['incid','R','IR'],'title',sprintf('%s COVID-19',incid.name),...
    'opt_I',options(...
    'plot_type','bar'),...
    'opt_IR',options('plot_type','bar'))
